apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
labels:
 prometheus: kube-prometheus
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: web
    interval: 30s