apiVersion: v1
kind: Service
metadata:
  name: influxdb-client
  namespace: kube-system
  labels:
    run: influxdb-client
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: influxdb-client